# Generated by Django 4.2.3 on 2023-07-13 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kit',
            name='type_kit',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
    ]
